/**:
  ros__parameters:
    machine_id: delta_marlin
    port: /dev/ttyACM
    baudrate: 250000
    accleration: 50 # mm / min^2
    x_max: 60  # mm
    y_max: 60  # mm
    z_max: 100  # mm
    default_v: 100  # mm / min
    x_max_v: 150  # mm / min
    y_max_v: 150  # mm / min
    z_max_v: 150  # mm / min
    x_steps: 100  # steps / mm
    y_steps: 100  # steps / mm
    z_steps: 100  # steps / mm

